#!/usr/bin/env bash
# script
hours=0
minutes=1

while [[ $hours -le 12 ]]; do
    while [[ $minutes -le 59 ]]; do
        printf "%02d:%02d\n" $hours $minutes
        minutes=$((minutes + 1))
    done
    minutes=0
    hours=$((hours + 1))
done | head -n 70
