#!/usr/bin/env bash
# script
count=0
hours=0
minutes=1

while [ $count -lt 70 ]; do
    printf "%02d:%02d\n" $hours $minutes
    minutes=$((minutes + 1))
    count=$((count + 1))

    if [ $minutes -gt 59 ]; then
        minutes=0
        hours=$((hours + 1))
    fi

    if [ $hours -gt 12 ]; then
        hours=0
    fi
done | head -n 70
