#!/usr/bin/env bash
# This script displays a list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest

