#!/usr/bin/env bash
# Script: 1-list_your_processes

get_command() {
    local pid=$1
    local cmd_path="/proc/$pid/cmdline"

    if [[ -r "$cmd_path" ]]; then
        local command=$(tr -s '\0' ' ' < "$cmd_path")
        echo "${command%% *}"
    fi
}

for pid_dir in /proc/[0-9]*; do
    pid=$(basename "$pid_dir")
    user=$(awk '/^Uid:/ {print $2}' "$pid_dir/status")
    tty=$(readlink "/proc/$pid/fd/0")
    ppid=$(awk '/^PPid:/ {print $2}' "$pid_dir/status")
    command=$(get_command "$pid")
    parent_command=$(get_command "$ppid")
    printf "%-10s %-5s %-10s %s\n" "$user" "$pid" "$parent_command" "$command"
done


