#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid containing its PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function love() {
    rm /var/run/myscript.pid
    echo "Exiting..."
    exit
}

trap "echo I hate the kill command; love" SIGTERM
trap "echo Y U no love me?!; love" SIGINT
trap "love" SIGQUIT

echo $$ > /var/run/myscript.pid
echo "To infinity and beyond"

while true; do
    sleep 1
done

