#!/usr/bin/env bash
# This script creates the file ~/holbertonscript.pid containing its PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file ~/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function love() {
    rm ~/holbertonscript.pid
    exit
}

trap "echo I hate the kill command; love" SIGTERM
trap "echo Y U no love me?!; love" SIGINT
trap "love" SIGQUIT

echo $$ > ~/holbertonscript.pid
while true; do
    echo "To infinity and beyond"
done

