#!/usr/bin/env bash
# This script kills the process 7-highlander
kill -9 "$(pgrep -f highlander)"#!/usr/bin/env bash
# This script kills the process 7-highlander
kill -9 "$(pgrep -f highlander)"#!/usr/bin/env bash
# This script kills the process 7-highlander
kill -9 "$(pgrep -f highlander)"#!/usr/bin/env bash
# This script kills the process 7-highlander
kill -9 "$(pgrep -f highlander)"#!/usr/bin/env bash
# This script kills the process 7-highlander
kill -9 "$(pgrep -f highlander)"#!/usr/bin/env bash
# This script kills the process 7-highlander
kill -9 "$(pgrep -f highlander)"#!/usr/bin/env bash
# This script kills the process 7-highlander
kill -9 "$(pgrep -f highlander)"
